name: push to swarm

on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload
        id: swarm-upload
        uses: ethersphere/swarm-actions/upload-dir@latest
        with:
          bee-url: ${{ secrets.SWARM_URL }}
          postage-batch-id: ${{ secrets.POSTAGE_STAMP }}
          dir: ./dist
          index-document: index.html
          timeout: 600000
          deferred: true

      - name: update feed
        id: swarm-feed
        uses: ethersphere/swarm-actions/write-feed@latest
        with:
          topic: datafund-website
          bee-url: ${{ secrets.SWARM_URL }}
          postage-batch-id: ${{ secrets.POSTAGE_STAMP }}
          reference: ${{ steps.swarm-upload.outputs.reference }}
          signer: ${{ secrets.SIGNER }}

      - name: print references
        run: |
          echo "upload ref: " ${{ steps.swarm-upload.outputs.reference }}
          echo "feed ref: " ${{ steps.swarm-feed.outputs.reference }}
          echo "CID: " ${{ steps.swarm-cid.outputs.cid }}
          echo "Feed Manifest: " ${{ steps.swarm-feed.outputs.manifest }}
